<div class="app-content">
                <div class="content-wrapper">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-xl-12">
                                <div class="card">
                                    <div class="card-header">
                                        <h1 class="card-title">SEO</h1>
                                    </div>
                                    <div class="card-body">
                                            <div id="page"><form method="POST" data-parsley-validate="" enctype="multipart/form-data" class="form-horizontal form-label-left"><!----> <div class="form-group"><label class="control-label col-md-3 col-sm-3 col-xs-12">
                    Meta title
                </label> <div class="col-md-9 col-sm-9 col-xs-12"><input type="text" class="form-control"></div></div> <div class="form-group"><label class="control-label col-md-3 col-sm-3 col-xs-12">
                    Meta keywords
                </label> <div class="col-md-9 col-sm-9 col-xs-12"><input type="text" class="form-control"></div></div> <div class="form-group"><label class="control-label col-md-3 col-sm-3 col-xs-12">
                    Meta description
                </label> <div class="col-md-9 col-sm-9 col-xs-12"><input type="text" class="form-control"></div></div> <div class="form-group"><label class="control-label col-md-3 col-sm-3 col-xs-12">
                    Meta author
                </label> <div class="col-md-9 col-sm-9 col-xs-12"><input type="text" class="form-control"></div></div> <div class="form-group"><label class="control-label col-md-3 col-sm-3 col-xs-12">
                    Google Analytics
                </label> <div class="col-md-9 col-sm-9 col-xs-12"><input type="text" class="form-control"> <small>[gtag('config', 'G-ER81WPCMK9')] bạn chỉ cần dán vào ID của tài khoản <code>G-ER81WPCMK9</code></small></div></div> <div class="form-group"><label class="control-label col-md-3 col-sm-3 col-xs-12">
                    Head scripts
                </label> <div class="col-md-9 col-sm-9 col-xs-12"><textarea rows="5" class="form-control"></textarea></div></div> <div class="form-group"><label class="control-label col-md-3 col-sm-3 col-xs-12">
                    Footer scripts
                </label> <div class="col-md-9 col-sm-9 col-xs-12"><textarea rows="5" class="form-control"></textarea></div></div> <div class="form-group"><label class="control-label col-md-3 col-sm-3 col-xs-12">
                    Google site verification
                </label> <div class="col-md-9 col-sm-9 col-xs-12"><input type="text" class="form-control"> <small>Bạn chỉ cần dán mã vào</small></div></div> <div class="form-group"><label class="control-label col-md-3 col-sm-3 col-xs-12">
                    Schema home name
                </label> <div class="col-md-9 col-sm-9 col-xs-12"><input type="text" class="form-control"></div></div> <div class="form-group"><label class="control-label col-md-3 col-sm-3 col-xs-12">
                    Schema home url
                </label> <div class="col-md-9 col-sm-9 col-xs-12"><input type="text" class="form-control"></div></div> <div class="form-group"><label class="control-label col-md-3 col-sm-3 col-xs-12">
                    Ngôn ngữ
                </label> <div class="col-md-9 col-sm-9 col-xs-12"><div class="el-select" style="width: 100%;"><!----><div class="el-input el-input--suffix"><!----><input type="text" readonly="readonly" autocomplete="off" placeholder="Chọn ngôn ngữ" class="el-input__inner"><!----><span class="el-input__suffix"><span class="el-input__suffix-inner"><i class="el-select__caret el-input__icon el-icon-arrow-up"></i><!----><!----><!----><!----><!----></span><!----></span><!----><!----></div><div class="el-select-dropdown el-popper" style="display: none; min-width: 634.8px;"><div class="el-scrollbar" style=""><div class="el-select-dropdown__wrap el-scrollbar__wrap" style="margin-bottom: -17px; margin-right: -17px;"><ul class="el-scrollbar__view el-select-dropdown__list"><!----><li class="el-select-dropdown__item selected"><span>VI</span></li> <li class="el-select-dropdown__item"><span>EN</span></li></ul></div><div class="el-scrollbar__bar is-horizontal"><div class="el-scrollbar__thumb" style="transform: translateX(0%);"></div></div><div class="el-scrollbar__bar is-vertical"><div class="el-scrollbar__thumb" style="transform: translateY(0%);"></div></div></div><!----></div></div></div></div> <div class="form-group"><label class="control-label col-md-3 col-sm-3 col-xs-12">
                    Tuỳ chỉnh Header
                </label> <div class="col-md-9 col-sm-9 col-xs-12"><p>Màu sắc <div class="el-color-picker"><!----><div class="el-color-picker__trigger"><span class="el-color-picker__color"><span class="el-color-picker__color-inner" style="background-color: transparent;"></span><span class="el-color-picker__empty el-icon-close"></span></span><span class="el-color-picker__icon el-icon-arrow-down" style="display: none;"></span></div><div class="el-color-dropdown el-color-picker__panel" style="display: none;"><div class="el-color-dropdown__main-wrapper"><div class="el-color-hue-slider is-vertical" style="float: right;"><div class="el-color-hue-slider__bar"></div><div class="el-color-hue-slider__thumb" style="left: 0px; top: 0px;"></div></div><div class="el-color-svpanel" style="background-color: rgb(255, 0, 0);"><div class="el-color-svpanel__white"></div><div class="el-color-svpanel__black"></div><div class="el-color-svpanel__cursor" style="top: 0px; left: 0px;"><div></div></div></div></div><!----><!----><div class="el-color-dropdown__btns"><span class="el-color-dropdown__value"><div class="el-input el-input--mini"><!----><input type="text" autocomplete="off" class="el-input__inner"><!----><!----><!----><!----></div></span><button type="button" class="el-button el-color-dropdown__link-btn el-button--text el-button--mini"><!----><!----><span>
        Xóa
      </span></button><button type="button" class="el-button el-color-dropdown__btn el-button--default el-button--mini is-plain"><!----><!----><span>
        OK
      </span></button></div></div></div></p> <p>Background <div class="el-color-picker"><!----><div class="el-color-picker__trigger"><span class="el-color-picker__color"><span class="el-color-picker__color-inner" style="background-color: transparent;"></span><span class="el-color-picker__empty el-icon-close"></span></span><span class="el-color-picker__icon el-icon-arrow-down" style="display: none;"></span></div><div class="el-color-dropdown el-color-picker__panel" style="display: none;"><div class="el-color-dropdown__main-wrapper"><div class="el-color-hue-slider is-vertical" style="float: right;"><div class="el-color-hue-slider__bar"></div><div class="el-color-hue-slider__thumb" style="left: 0px; top: 0px;"></div></div><div class="el-color-svpanel" style="background-color: rgb(255, 0, 0);"><div class="el-color-svpanel__white"></div><div class="el-color-svpanel__black"></div><div class="el-color-svpanel__cursor" style="top: 0px; left: 0px;"><div></div></div></div></div><!----><!----><div class="el-color-dropdown__btns"><span class="el-color-dropdown__value"><div class="el-input el-input--mini"><!----><input type="text" autocomplete="off" class="el-input__inner"><!----><!----><!----><!----></div></span><button type="button" class="el-button el-color-dropdown__link-btn el-button--text el-button--mini"><!----><!----><span>
        Xóa
      </span></button><button type="button" class="el-button el-color-dropdown__btn el-button--default el-button--mini is-plain"><!----><!----><span>
        OK
      </span></button></div></div></div></p> <p></p><div class="col-md-3 col-sm-12 col-xs-12"><label class="form-label">Ảnh nền</label> <div class="cs-image"><div class="cs-image-upload"><div tabindex="0" class="el-upload el-upload--text"><i class="el-icon-plus avatar-uploader-icon"></i><input type="file" name="file" class="el-upload__input"></div></div> <a class="el-link el-link--default"><!----><span class="el-link--inner">Xoá</span><!----></a></div></div> <p></p></div></div> <div class="form-group"><label class="control-label col-md-3 col-sm-3 col-xs-12">
                    Tuỳ chỉnh Footer
                </label> <div class="col-md-9 col-sm-9 col-xs-12"><p>Màu sắc  <div class="el-color-picker"><!----><div class="el-color-picker__trigger"><span class="el-color-picker__color"><span class="el-color-picker__color-inner" style="background-color: transparent;"></span><span class="el-color-picker__empty el-icon-close"></span></span><span class="el-color-picker__icon el-icon-arrow-down" style="display: none;"></span></div><div class="el-color-dropdown el-color-picker__panel" style="display: none;"><div class="el-color-dropdown__main-wrapper"><div class="el-color-hue-slider is-vertical" style="float: right;"><div class="el-color-hue-slider__bar"></div><div class="el-color-hue-slider__thumb" style="left: 0px; top: 0px;"></div></div><div class="el-color-svpanel" style="background-color: rgb(255, 0, 0);"><div class="el-color-svpanel__white"></div><div class="el-color-svpanel__black"></div><div class="el-color-svpanel__cursor" style="top: 0px; left: 0px;"><div></div></div></div></div><!----><!----><div class="el-color-dropdown__btns"><span class="el-color-dropdown__value"><div class="el-input el-input--mini"><!----><input type="text" autocomplete="off" class="el-input__inner"><!----><!----><!----><!----></div></span><button type="button" class="el-button el-color-dropdown__link-btn el-button--text el-button--mini"><!----><!----><span>
        Xóa
      </span></button><button type="button" class="el-button el-color-dropdown__btn el-button--default el-button--mini is-plain"><!----><!----><span>
        OK
      </span></button></div></div></div></p> <p>Màu nền <div class="el-color-picker"><!----><div class="el-color-picker__trigger"><span class="el-color-picker__color"><span class="el-color-picker__color-inner" style="background-color: transparent;"></span><span class="el-color-picker__empty el-icon-close"></span></span><span class="el-color-picker__icon el-icon-arrow-down" style="display: none;"></span></div><div class="el-color-dropdown el-color-picker__panel" style="display: none;"><div class="el-color-dropdown__main-wrapper"><div class="el-color-hue-slider is-vertical" style="float: right;"><div class="el-color-hue-slider__bar"></div><div class="el-color-hue-slider__thumb" style="left: 0px; top: 0px;"></div></div><div class="el-color-svpanel" style="background-color: rgb(255, 0, 0);"><div class="el-color-svpanel__white"></div><div class="el-color-svpanel__black"></div><div class="el-color-svpanel__cursor" style="top: 0px; left: 0px;"><div></div></div></div></div><!----><!----><div class="el-color-dropdown__btns"><span class="el-color-dropdown__value"><div class="el-input el-input--mini"><!----><input type="text" autocomplete="off" class="el-input__inner"><!----><!----><!----><!----></div></span><button type="button" class="el-button el-color-dropdown__link-btn el-button--text el-button--mini"><!----><!----><span>
        Xóa
      </span></button><button type="button" class="el-button el-color-dropdown__btn el-button--default el-button--mini is-plain"><!----><!----><span>
        OK
      </span></button></div></div></div></p> <p></p><div class="col-md-3 col-sm-12 col-xs-12"><label class="form-label">Ảnh nền</label> <div class="cs-image"><div class="cs-image-upload"><div tabindex="0" class="el-upload el-upload--text"><i class="el-icon-plus avatar-uploader-icon"></i><input type="file" name="file" class="el-upload__input"></div></div> <a class="el-link el-link--default"><!----><span class="el-link--inner">Xoá</span><!----></a></div></div> <p></p></div></div> <div class="form-group"><div class="control-label col-md-12 col-sm-12 col-xs-12 text-right"><button type="button" class="btn btn-success">Submit</button></div></div></form> <input type="hidden" id="postAjax" value="https://admin.hoidoanhnghiepquan1.com/config/post/ajax"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>