<div class="app-content">
                <div class="content-wrapper">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-xl-12">
                                <div class="card">
                                    <div class="card-header">
                                        <h1 class="card-title">Menu</h1>
                                    </div>
                                    <div class="card-body">
                                            <div id="page"><div class="row"><div class="col-md-12 col-sm-12 col-xs-12"><div class="row"><div class="col-md-12 col-sm-12 col-xs-12"><div class="el-select"><!----><div class="el-input el-input--suffix"><!----><input type="text" readonly="readonly" autocomplete="off" placeholder="Chọn nhóm" class="el-input__inner"><!----><span class="el-input__suffix"><span class="el-input__suffix-inner"><i class="el-select__caret el-input__icon el-icon-arrow-up"></i><!----><!----><!----><!----><!----></span><!----></span><!----><!----></div><div class="el-select-dropdown el-popper" style="display: none; min-width: 217.8px;"><div class="el-scrollbar" style=""><div class="el-select-dropdown__wrap el-scrollbar__wrap" style="margin-bottom: -17px; margin-right: -17px;"><ul class="el-scrollbar__view el-select-dropdown__list"><!----><li class="el-select-dropdown__item"><span>Main menu</span></li><li class="el-select-dropdown__item"><span>dangtu</span></li></ul></div><div class="el-scrollbar__bar is-horizontal"><div class="el-scrollbar__thumb" style="transform: translateX(0%);"></div></div><div class="el-scrollbar__bar is-vertical"><div class="el-scrollbar__thumb" style="transform: translateY(0%);"></div></div></div><!----></div></div> <div class="el-select"><!----><div class="el-input el-input--suffix"><!----><input type="text" readonly="readonly" autocomplete="off" placeholder="Chọn ngôn ngữ" class="el-input__inner"><!----><span class="el-input__suffix"><span class="el-input__suffix-inner"><i class="el-select__caret el-input__icon el-icon-arrow-up"></i><!----><!----><!----><!----><!----></span><!----></span><!----><!----></div><div class="el-select-dropdown el-popper" style="display: none; min-width: 217.8px;"><div class="el-scrollbar" style=""><div class="el-select-dropdown__wrap el-scrollbar__wrap" style="margin-bottom: -17px; margin-right: -17px;"><ul class="el-scrollbar__view el-select-dropdown__list"><!----><li class="el-select-dropdown__item selected"><span>VI</span></li> <li class="el-select-dropdown__item"><span>EN</span></li></ul></div><div class="el-scrollbar__bar is-horizontal"><div class="el-scrollbar__thumb" style="transform: translateX(0%);"></div></div><div class="el-scrollbar__bar is-vertical"><div class="el-scrollbar__thumb" style="transform: translateY(0%);"></div></div></div><!----></div></div> <button type="button" class="el-button el-button--primary"><!----><!----><span>Tạo nhóm</span></button> <button type="button" class="el-button el-button--primary"><!----><!----><span>Sửa nhóm</span></button> <!----></div></div> <div class="el-row" style="margin-left: -10px; margin-right: -10px;"><div class="el-col el-col-24" style="padding-left: 10px; padding-right: 10px;"><div id="links-output"></div> <div id="links" class="dd mt-3"><ol class="dd-list"></ol></div></div></div></div> <div class="cs-tool"><button type="button" class="btn btn-success"><i class="material-icons">add</i> Lưu thay đổi
                </button></div></div> <div class="el-dialog__wrapper" style="display: none;"><div role="dialog" aria-modal="true" aria-label="Nhóm" class="el-dialog" style="margin-top: 15vh; width: 420px;"><div class="el-dialog__header"><span class="el-dialog__title">Nhóm</span><button type="button" aria-label="Close" class="el-dialog__headerbtn"><i class="el-dialog__close el-icon el-icon-close"></i></button></div><!----><!----></div></div> <div class="el-dialog__wrapper" style="display: none;"><div role="dialog" aria-modal="true" aria-label="Nhóm" class="el-dialog" style="margin-top: 15vh; width: 420px;"><div class="el-dialog__header"><span class="el-dialog__title">Nhóm</span><button type="button" aria-label="Close" class="el-dialog__headerbtn"><i class="el-dialog__close el-icon el-icon-close"></i></button></div><!----><!----></div></div> <div class="el-dialog__wrapper" style="display: none;"><div role="dialog" aria-modal="true" aria-label="Link" class="el-dialog" style="margin-top: 15vh; width: 420px;"><div class="el-dialog__header"><span class="el-dialog__title">Link</span><button type="button" aria-label="Close" class="el-dialog__headerbtn"><i class="el-dialog__close el-icon el-icon-close"></i></button></div><!----><!----></div></div> <input type="hidden" id="postAjax" value="https://admin.hoidoanhnghiepquan1.com/link/group/post/ajax"> <input type="hidden" id="postLinkAjax" value="https://admin.hoidoanhnghiepquan1.com/link/post/ajax"> <input type="hidden" id="sortedLinkPostAjax" value="https://admin.hoidoanhnghiepquan1.com/link/sorted/post/ajax"> <input type="hidden" id="searchAjax" value="https://admin.hoidoanhnghiepquan1.com/link"> <input type="hidden" id="detailAjax" value="https://admin.hoidoanhnghiepquan1.com/link/detail"> <input type="hidden" id="removeAjax" value="https://admin.hoidoanhnghiepquan1.com/link/remove"> <input type="hidden" id="linkGroupDetailAjax" value="https://admin.hoidoanhnghiepquan1.com/ajax/link/group/detail"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>